'use client';

import React, { useState, useEffect } from 'react';
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle
} from '@/components/ui/dialog';
import { Button } from '@/components/ui/button';
import { Checkbox } from '@/components/ui/checkbox';
import { ScrollArea } from '@/components/ui/scroll-area';
import { AlertTriangle } from 'lucide-react';
import { supabase } from '@/lib/supabase/client';

interface DisclaimerModalProps {
  userId: string | undefined;
  email?: string | undefined;
}

export function DisclaimerModal({ userId, email }: DisclaimerModalProps) {
  const [open, setOpen] = useState(false);
  const [hasAgreed, setHasAgreed] = useState(false);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    if (!userId) return;

    const checkDisclaimer = async () => {
      try {
        // Fetch the user's profile to check disclaimer_agreed_at
        const { data: profile, error } = await supabase
          .from('profiles')
          .select('disclaimer_agreed_at')
          .eq('id', userId)
          .single();

        if (error) {
          if (error.code !== 'PGRST116') {
            console.error('Error fetching profile:', error);
          }
          setOpen(true);
          setLoading(false);
          return;
        }

        if (!profile?.disclaimer_agreed_at) {
          setOpen(true);
          setLoading(false);
          return;
        }

        const lastAgreedDate = new Date(profile.disclaimer_agreed_at);
        const now = new Date();
        const isSameMonth =
          lastAgreedDate.getMonth() === now.getMonth() &&
          lastAgreedDate.getFullYear() === now.getFullYear();

        if (!isSameMonth) {
          setOpen(true);
        }

        setLoading(false);
      } catch (err) {
        console.error('Unexpected error:', err);
        setOpen(true);
        setLoading(false);
      }
    };

    checkDisclaimer();
  }, [userId]);

  const handleAgree = async () => {
    if (!hasAgreed || !userId) return;

    try {
      // Upsert the profile with the current timestamp
      const { error } = await supabase
        .from('profiles')
        .upsert({
          id: userId,
          email: email || '',
          disclaimer_agreed_at: new Date().toISOString()
        });

      if (error) {
        console.error('Error saving disclaimer agreement:', error);
        alert('Failed to save agreement. Please try again.');
        return;
      }

      setOpen(false);
    } catch (err) {
      console.error('Unexpected error:', err);
      alert('An unexpected error occurred. Please try again.');
    }
  };

  const disclaimerText =
    `ONLINE PUMP & HYDRAULIC SIZING TOOL – TERMS OF USE / DISCLAIMER
(Must be accepted before proceeding)

By clicking "I Agree", "Continue", or otherwise using this tool (the Tool), you acknowledge and agree to the following, on behalf of yourself and any company, client, principal, or end user for whom you act. If you do not agree, you must not use the Tool.

1. No engineering, design, or professional advice
• The Tool provides general, indicative calculations only.
• It is not consulting advice, engineering certification, hydraulic design, or a statement of compliance with AS/NZS, NCC/BCA, WSAA, local council, water authority, fire, electrical, or workplace standards.
• All outputs must be reviewed, checked, and approved by a suitably qualified engineer/designer before being used, issued, constructed, installed, or relied on.

2. Data, assumptions, and limits
• Tool results depend on user inputs, default assumptions, formulas, and manufacturer data that may change, be incomplete, be wrong, or not match site conditions.
• Actual system performance depends on pipework, friction losses, installation quality, voltage, control philosophy, fluid properties, fouling, wear, NPSH conditions, and other factors outside our control.
• The Tool does not and cannot account for every application, product variation, or site constraint.

3. User responsibilities
You are solely responsible to:
• verify all flows, heads, duty points, rainfall/stormwater allowances, runoff coefficients, safety factors, and storage volumes against the relevant authority's requirements;
• confirm pump materials, electrical ratings, and control gear suit the fluid, temperature, and environment;
• confirm the selected pump/system is suitable for the actual installation;
• obtain independent professional advice where required;
• comply with all laws, codes, approvals, and customer specifications.

4. No guarantee of suitability or accuracy
• The Tool is provided "as is" and "as available."
• We do not warrant that any selection, calculation, or recommendation is correct, complete, current, or fit for your purpose.
• Pump/system selections generated by the Tool are suggested only and may not be available, may be superseded, or may require accessories (controls, valves, basins, guides, stands, rails, electrical protection, etc.) that are not shown in the Tool.

5. No liability
To the maximum extent permitted by law (including the Australian Consumer Law, where it applies):
• we exclude all liability for any loss, damage, claim, cost, or expense of any kind, whether direct, indirect, incidental, consequential, special, exemplary, economic, or punitive, arising out of or in connection with your use or inability to use the Tool;
• we specifically exclude liability for:
  – incorrect pump sizing or selection;
  – flooding, surcharge, property damage, mould, business interruption, or loss of profit;
  – personal injury or death caused by incorrect design, installation, access, lifting, electrical work, or maintenance;
  – failure to meet authority, council, or insurance requirements;
  – reliance on outdated or placeholder data;
  – third-party or manufacturer changes;
  – integration or API errors.
• where liability cannot be excluded, it is limited to re-supplying the service or paying the cost of having it re-supplied.

6. Indemnity
You indemnify and hold us harmless from and against any claim, loss, damage, liability, cost, or expense (including legal costs on a full indemnity basis) arising out of or in connection with:
• your use or misuse of the Tool;
• your failure to obtain proper engineering/design approval;
• your provision of incorrect, incomplete, or misleading inputs;
• your supply of Tool outputs to a third party;
• any claim brought by your customer, builder, plumber, authority, or end user relying on Tool outputs.

7. Third-party products and data
Where the Tool references or displays manufacturer/supplier data, that data remains the property and responsibility of the relevant manufacturer/supplier and may change without notice. You must confirm all performance, materials, and dimensions from the current technical literature before ordering or installing.

8. No promise of availability
We may change, update, suspend, or withdraw the Tool, individual functions, or data sets at any time without notice. We are not responsible for downtime, internet issues, browser issues, or integration failures.

9. Commercial/beta/experimental features
Some functions may be experimental, in beta, or not yet validated for all regions or standards. You use these entirely at your own risk.

10. Governing law
These terms are governed by the laws of Queensland, Australia, and you submit to the non-exclusive jurisdiction of the courts of Queensland.

By clicking "I Agree" you confirm that you have read and understood this disclaimer, that you are competent to assess or have had it assessed by a qualified person, and that you accept all risks associated with using this Tool.

Last Updated: November 2025`.trim();

  if (loading) {
    return null; // Or return a loading spinner
  }

  return (
    <Dialog open={open} onOpenChange={() => {}}>
      <DialogContent
        className='no-scrollbar max-h-[95vh] max-w-[60vw] min-w-[50vw] overflow-y-auto p-4'
        onPointerDownOutside={(e) => e.preventDefault()}
        onEscapeKeyDown={(e) => e.preventDefault()}
      >
        <DialogHeader>
          <DialogTitle className='flex items-center gap-2 text-xl'>
            <AlertTriangle className='h-6 w-6 text-red-600' />
            Terms of Use - Must Be Accepted to Proceed
          </DialogTitle>
          <DialogDescription className='text-sm'>
            This tool provides indicative calculations only. Professional
            verification is required before use.
          </DialogDescription>
        </DialogHeader>

        <ScrollArea className='my-4 w-full flex-1 rounded-md border p-5'>
          <div className='text-sm leading-relaxed font-medium whitespace-pre-wrap'>
            {disclaimerText}
          </div>
        </ScrollArea>

        <div className='flex items-start gap-3 rounded-lg border border-amber-200 p-4'>
          <Checkbox
            id='agree'
            checked={hasAgreed}
            onCheckedChange={(checked) => setHasAgreed(checked === true)}
            className='mt-1 data-[state=checked]:border-amber-600 data-[state=checked]:bg-amber-600'
          />
          <label
            htmlFor='agree'
            className='cursor-pointer text-sm leading-relaxed font-medium'
          >
            I have read and understood the disclaimer above. I confirm that I am
            competent to assess the outputs or will have them reviewed by a
            qualified professional before use.
          </label>
        </div>

        <DialogFooter>
          <Button
            onClick={handleAgree}
            disabled={!hasAgreed}
            className='w-full bg-green-600 font-semibold text-white hover:bg-green-700 sm:w-auto'
          >
            I Agree - Continue to Tool
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}
